### PR TITLE
db/models: makeover! refactor main APIs, doctests, PEP8

### PR DESCRIPTION
**Pull request by auscompgeek**
These are fairly large changes (or rather, a very long list of changes), so I think we should get a few different pairs of eyes before merging this.

API changes:
- `Model.query()` has been renamed to `Model._query()`.
- `Model._query()` returns rows rather than class instances, so specific fields can be queried rather than whole columns.
  - `Model.find()` and `Model.find_all()` still return class instances, as before.
  - See `User.check_login()` for an example.
- `Model._query()` now takes `id` as a keyword arg and is translated to the correct field name when querying the database.
- `Model.delete()` has been renamed to `Model.delete_where()`.
- A `Model.delete(self)` has been added which deletes an object from the database, using its `id`.
  - i.e. with an instance of `User` called `user`, you can now call `user.delete()` and expect the correct user to be deleted.
  - This is yet to be implemented for objects that _don't_ have an `id` attribute. Pull requests for those welcome.
- `Model.delete_all()` has been removed, since it had no use and duplicated the functionality of `Model.delete()`.
- Add a `Model.find_iter()`, which generates objects rather than returning a list of objects.
  - This requires an extra `_iter` keyword argument to `Model._query()`, which right now returns its cursor object...
- `Model` now inherits from `object`.
- `Game.get_answers(question_id)` has been moved to `Question.get_answers()`, as one would expect.

Bugfixes:
- Fixed trivial errors in `User.set_email()`, `User.set_password()`, `Category.create()`, and `Question.update_score()`, all of which, oddly enough, aren't being used yet.
- The signatures of the `Model.__init__()` and `Model.create()` stubs have been fixed.

Misc:
- Added doctests.
- Removed debug code.
- `Game()` now gives a more descriptive error message when no questions are given.
- PEP-8-ified! I've mostly ignored long line errors though.
- Added an `__all__` list and a module docstring.
- Added a useful generic `.__repr__()` method.

### CODE REVIEW

**Comment by auscompgeek** [comment]
Actually, whilst I'm at it, I'll add a `Model.find_iter()`. This requires a change to `Model._query()` to return an iterable of rows (when given the `_iter` kwarg). Right now, this returns the cursor object, which might be bad...

Updated the OP.

**Comment by fourkbomb** [comment]
:+1::shipit:

**Comment by paked** [comment]
Are we merging this in?

**Comment by auscompgeek** [comment]
@paked I'm waiting for review. So far, nobody (except @keepcalm444) has reviewed this PR yet.

**Comment by paked** [comment]
:+1: :100: :shipit:

**Comment by lkw657** [comment]
It seems fine

**Pull request merged**
